fix: avoid validating checksums for partial responses
googleapis/google-resumable-media-python pull request #361
Opened 2022-10-04 15:14 UTC by simonbohnen

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-resumable-media-python/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #362 🦕

2022-10-04 16:21 UTC, parthea commented
Hi @simonbohnen,

Please could you sign the CLA?
https://cla.developers.google.com/about

2022-10-04 16:44 UTC, simonbohnen commented
> Hi @simonbohnen,
> 
> Please could you sign the CLA? https://cla.developers.google.com/about

It looks like I did for my work account (SimonBohnenQC). Is there a way to re-run the check?
![Screen Shot 2022-10-04 at 18 42 36](https://user-images.githubusercontent.com/26229617/193877968-e5d80e54-ca5d-476a-958a-a6b4879d0aec.png)

2022-10-05 15:10 UTC, parthea commented
@cojenco Please could you take a look?

2022-10-07 17:45 UTC, cojenco commented
> > Hi @simonbohnen,
> > Please could you sign the CLA? https://cla.developers.google.com/about
> 
> It looks like I did for my work account (SimonBohnenQC). Is there a way to re-run the check? ![Screen Shot 2022-10-04 at 18 42 36](https://user-images.githubusercontent.com/26229617/193877968-e5d80e54-ca5d-476a-958a-a6b4879d0aec.png)

I force rescanned the CLA and it's passing now. Our team will work on reviewing your PR. Thanks for your contribution!

2022-10-17 23:42 UTC, cojenco requested changes
Thanks @simonbohnen for the fix. I agree we want to skip checksum validations for partial content responses, as noted in our documentation.

In addition to the comments, could you add a unit test for this? Something alongside the tests [here](https://github.com/googleapis/google-resumable-media-python/blob/main/tests/unit/requests/test_download.py#L81). Let me know if you'd like assistance on testing.

2022-10-17 23:42 UTC, cojenco commented on google/resumable_media/requests/download.py
> +        if expected_checksum is not None and response.status_code != 206:
Let's check the status code against `http.client.PARTIAL_CONTENT`

2022-10-17 23:42 UTC, cojenco commented on google/resumable_media/requests/download.py
> +        if expected_checksum is not None and response.status_code != 206:
Same for the other places, let's use `http.client.PARTIAL_CONTENT`

2022-10-21 16:50 UTC, simonbohnen commented
> Thanks @simonbohnen for the fix. I agree we want to skip checksum validations for partial content responses, as noted in our documentation.
> 
> 
> 
> In addition to the comments, could you add a unit test for this? Something alongside the tests [here](https://github.com/googleapis/google-resumable-media-python/blob/main/tests/unit/requests/test_download.py#L81). Let me know if you'd like assistance on testing. 

I'll add some tests next week👌🏼

2022-10-24 12:51 UTC, simonbohnen commented
Can you help me with this error? The commit messages look good to me 🤔
<img width="398" alt="Screen Shot 2022-10-24 at 14 51 21" src="https://user-images.githubusercontent.com/26229617/197529511-80007e5c-0118-4881-b3b6-8aa494e68c81.png">

2022-10-28 23:10 UTC, cojenco reviewed
Thanks for adding tests @simonbohnen 

Besides the lint error on unused `ret_val` in the tests, LGTM. Try running `nox -s lint` to check linting.

2022-11-01 20:37 UTC, cojenco approved these changes
LGTM, thanks again for your contribution!

2022-11-01 23:03 UTC, merged